name: time-series-final-work-env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python
  - openpyxl
  - jupyterlab
  - ipykernel
  - matplotlib
  - numpy
  - statsmodels
  - pmdarima
  - fbprophet
